name: Run benchmarks
on:
  push:
    branches:
      - benchmark  # TODO set to master when deploying

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest  # TODO runs-on: self-hosted
    container:
      image: firedrakeproject/firedrake-vanilla:latest
    env:
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
    steps:
      - name: Fix permissions
        run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
      - name: Install benchmark dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install -e .
          python -m pip install pytest pytest-benchmark
      - name: Run benchmarks
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pytest --benchmark-only --benchmark-json output.json --verbose benchmarks tests
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@connorjward'
